name: Builder

on:
  push:
    branches: "*"
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/builder.yml"
    tags:
      - 'v[0-9]+.*'
  pull_request:
    branches: "*"
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/builder.yml"
  workflow_dispatch:

env:
  PRODUCT: Beacon
  CGO_ENABLED: 0
  GO111MODULE: on

jobs:
  build:
    name: ${{ matrix.job.GOOS }}-${{ matrix.job.GOARCH }} (${{ matrix.job.os }})
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { GOOS: "windows", GOARCH: "amd64", os: "windows-latest" }
          - { GOOS: "windows", GOARCH: "386", os: "windows-latest" }
          - { GOOS: "windows", GOARCH: "arm64", os: "windows-latest" }
          - { GOOS: "darwin", GOARCH: "amd64", os: "macos-latest" }
          - { GOOS: "darwin", GOARCH: "arm64", os: "macos-latest" }
          - { GOOS: "linux", GOARCH: "amd64", os: "ubuntu-latest" }
          - { GOOS: "linux", GOARCH: "386", os: "ubuntu-latest" }
          - { GOOS: "linux", GOARCH: "arm64", os: "ubuntu-latest" }
        exclude:
          - job: { GOOS: "darwin", GOARCH: "386", os: "macos-latest" }
    continue-on-error: true
    env:
      GOOS: ${{ matrix.job.GOOS }}
      GOARCH: ${{ matrix.job.GOARCH }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Check out code base
        if: github.event_name == 'push'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check out code base
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Cache go module
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm and dependencies
        run: |
          npm install -g pnpm
          cd server/frontend
          pnpm install

      - name: Pnpm Build
        run: |
          cd server/frontend
          pnpm build

      - name: Build binary
        id: builder
        shell: bash
        run: |
          ARGS="${GOOS}-${GOARCH}"
          go build -trimpath --ldflags "-s -w -buildid=" -v -o ./bin/${{ env.PRODUCT }}-${ARGS}
          # echo "filename=${{ env.PRODUCT }}-${ARGS}" >> $GITHUB_OUTPUT
          echo "BIN_PATH=./bin/${{ env.PRODUCT }}-${ARGS}" >> $GITHUB_OUTPUT

      - name: Check for release
        id: is-release
        shell: bash
        run: |
          unset IS_RELEASE ; if [[ $GITHUB_REF =~ ^refs/tags/v[0-9].* ]]; then IS_RELEASE='true' ; fi
          echo "IS_RELEASE=${IS_RELEASE}" >> $GITHUB_OUTPUT

      - name: Extract version from tag
        if: steps.is-release.outputs.IS_RELEASE
        id: extract_version
        shell: bash
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Create tarball
        if: steps.is-release.outputs.IS_RELEASE
        id: package
        shell: bash
        run: |
          PKG_suffix=".tar.gz" ; case ${{ matrix.job.GOOS }} in *windows*) PKG_suffix=".zip" ;; esac;
          TARGET="${{ matrix.job.GOOS }}-${{ matrix.job.GOARCH }}"
          PKG_BASENAME=${{ env.PRODUCT }}-${{ env.VERSION }}-${TARGET}
          PKG_NAME=${PKG_BASENAME}${PKG_suffix}
          echo "PKG_NAME=${PKG_NAME}" >> $GITHUB_OUTPUT
          PKG_STAGING="./package"
          ARCHIVE_DIR="${PKG_STAGING}/${PKG_BASENAME}/"
          mkdir -p "${ARCHIVE_DIR}"
          # Binary
          cp "${{ steps.builder.outputs.BIN_PATH }}" "$ARCHIVE_DIR"
          # README, LICENSE and CHANGELOG files
          cp "README.md" "$ARCHIVE_DIR"
          # base compressed package
          pushd "${PKG_STAGING}/" >/dev/null
          case ${{ matrix.job.GOOS }} in
            windows) 7z -y a "${PKG_NAME}" "${PKG_BASENAME}"/* | tail -2 ;;
            *) tar czf "${PKG_NAME}" "${PKG_BASENAME}"/* ;;
          esac;
          popd >/dev/null
          # Let subsequent steps know where to find the compressed package
          echo "PKG_PATH=${PKG_STAGING}/${PKG_NAME}" >> $GITHUB_OUTPUT

      - name: Extract release notes
        if: steps.is-release.outputs.IS_RELEASE
        id: release_notes
        shell: bash
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          RELEASE_NOTES=$(awk '/## \['$VERSION'\]/{flag=1;next} /## \[/ {flag=0} flag' CHANGELOG.md)
          echo $RELEASE_NOTES
          {
            echo "body<<EOF"
            echo "${RELEASE_NOTES}"
            echo EOF
          } >> $GITHUB_ENV

      - name: Generate checksums
        if: steps.is-release.outputs.IS_RELEASE
        shell: bash
        run: |
          cd package
          if [ "$GOOS" = "darwin" ]; then
            find . -type f \( -name "*.tar.gz" -o -name "*.zip" \) -exec shasum -a 256 {} \; > ${{ env.PRODUCT }}-${{ env.VERSION }}-${{ env.GOOS }}-${{ env.GOARCH }}-checksums.txt
          else
            find . -type f \( -name "*.tar.gz" -o -name "*.zip" \) -exec sha256sum {} \; > ${{ env.PRODUCT }}-${{ env.VERSION }}-${{ env.GOOS }}-${{ env.GOARCH }}-checksums.txt
          fi
          mv ${{ env.PRODUCT }}-${{ env.VERSION }}-${{ env.GOOS }}-${{ env.GOARCH }}-checksums.txt $GITHUB_WORKSPACE/
          cat $GITHUB_WORKSPACE/${{ env.PRODUCT }}-${{ env.VERSION }}-${{ env.GOOS }}-${{ env.GOARCH }}-checksums.txt

      - name: Upload checksums
        if: steps.is-release.outputs.IS_RELEASE
        uses: actions/upload-artifact@v4
        with:
          name: checksums-${{ env.GOOS }}-${{ env.GOARCH }}
          path: ${{ env.PRODUCT }}-${{ env.VERSION }}-${{ env.GOOS }}-${{ env.GOARCH }}-checksums.txt

      - name: Publish archives and packages
        uses: softprops/action-gh-release@v1
        if: steps.is-release.outputs.IS_RELEASE
        with:
          body: ${{ env.body }}
          files: |
            # ${{ env.PRODUCT }}-${{ env.VERSION }}-checksums.txt
            ${{ steps.package.outputs.PKG_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  collect:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check for release
        id: is-release
        shell: bash
        run: |
          unset IS_RELEASE ; if [[ $GITHUB_REF =~ ^refs/tags/v[0-9].* ]]; then IS_RELEASE='true' ; fi
          echo "IS_RELEASE=${IS_RELEASE}" >> $GITHUB_OUTPUT
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Download all artifacts
        if: steps.is-release.outputs.IS_RELEASE
        uses: actions/download-artifact@v4

      - name: Combine checksums
        if: steps.is-release.outputs.IS_RELEASE
        run: |
          pwd
          ls -lath
          tree
          # find . -name "*-checksums.txt" ! -name "Beacon-v0.1.3-checksums.txt" | xargs -I {} sh -c 'cat {}; echo'
          find . -name "*-checksums.txt" ! -name "${{ env.PRODUCT }}-${{ env.VERSION }}-checksums.txt" | xargs cat > ${{ env.PRODUCT }}-${{ env.VERSION }}-checksums.txt

      - name: Publish archives and packages
        if: steps.is-release.outputs.IS_RELEASE
        uses: softprops/action-gh-release@v1
        with:
          # body: ${{ steps.release_notes.outputs.body }}
          files: |
            ${{ env.PRODUCT }}-${{ env.VERSION }}-checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}